### ISSUE TITLE
version 0.6.4 is missing "main" key in package.json

### ISSUE THREAD

**Issue by mdiplacido** [microsoft/angular-react#118]
I don't see a main or module key in package.json or any reference to js in the package.json file.  my build tools are not able to resolve the JS for this version.  Going to have to move back to an older version for now...

**Comment by bengry** [comment]
@dorgold looks like this was not published using the appropriate scripts. Use the `publish:core` and `publish:fabric` scripts from the root `package.json`.

**Comment by dorgold** [comment]
Fixed, released version [v0.6.5 ](https://github.com/microsoft/angular-react/releases/tag/v0.6.5) now. Sorry for the confusion.

**Comment by mdiplacido** [comment]
Thanks much!  Will try the latest version later today.

**Comment by mdiplacido** [comment]
Just tried version 0.6.5, things are looking good, my toolchain is working properly now.
