### ISSUE TITLE
Invalid links in wiki

### ISSUE THREAD

**Issue by acharlop** [microsoft/angular-react#131]
In the [Architecture](https://github.com/Microsoft/angular-react/wiki/Architecture%3A-High-level#concepts) page `Architecture:-High-level.md` twice an incorrect link is used.

Line 19: `[more on that here](https://TODO)`
Line 25: `[caveats](https://TODO)`

**Comment by aarongreenwald** [comment]
@acharlop, thanks for bringing this to my attention. The wiki really does need updating - looks like it was a WIP that never got finished. In the meantime, I updated one of the links and removed the other.
