### ISSUE TITLE
ng serve throws errors

### ISSUE THREAD

**Issue by Dav2070** [microsoft/angular-react#134]
Hi there, I want to use angular-react with Fabric, but it doesn't work. 
Whenever I import a module and run `ng serve`, it throws some errors.

![image](https://user-images.githubusercontent.com/16546287/62877780-129aff00-bd28-11e9-9d2e-93821e348462.png)

`ERROR in node_modules/@angular-react/fabric/src/lib/components/callout/callout.component.d.ts(7,34): error TS2339: Property 'componentRef' does not exist on type 'ICalloutProps'.`
`node_modules/@angular-react/fabric/src/lib/components/image/image.component.d.ts(5,32): error TS2339: Property 'componentRef' does not exist on type 'IImageProps'.`

I'm using following package versions:
* Angular 8
* @angular-react/fabric: 1.0.2
* office-ui-fabric-react: 6.200.0
* rxjs: 6.5.2
* react: 16.9.0
* react-dom: 16.9.0

Running on Ubuntu 18.04 on Windows 10.
Depending on which versions of the packages I use, there are different errors.

Any ideas on how to fix this are very appreciated. Thanks!

**Comment by aarongreenwald** [comment]
Hi @Dav2070, thanks for your patience - I am experimenting with a minimal project trying to reproduce this error and I'm now getting other errors, as you mentioned. So I went and checked what we have in our production project that we know works. 

* @angular/core: 8.1.3
* @angular-react/fabric: 1.0.2
* @angular-react/core: 1.0.1
* office-ui-fabric-react: 6.151.0
* react: 16.8.6
* react-dom: 16.8.6
* typescript: 3.4.5

Two things stand out to me: your office-ui-fabric-react version is higher, which _could_ cause some differences, and you didn't list what version of @angular-react/core you have, but the listed peer dependency in @angular-react/fabric is incorrect - it says `0.6.2` but it should be `^1.0.0`.

I'm going to fix the listed peer dependency, and if you'd like to try to use 6.151.0 for office-ui-fabric-react and let me know what happens that would be great. 

Thanks!

**Comment by aarongreenwald** [comment]
One workaround you can try is to turn on `skipLibCheck` in your tsconfig. It's not ideal because it will cause typescript to not check any libraries, but it should get you past this issue for now and unblock you. I'm still going to try to figure out what these incompatibilities are.

**Comment by Dav2070** [comment]
Hi, thanks for the response! I tried different combinations of package versions with the following results:

This is the same configuration as in my original post, but with `@angular-react/fabric 1.0.3`, but it shows the same error:
- @angular-react/core: 1.0.1
- @angular-react/fabric: 1.0.2 / 1.0.3
- office-ui-fabric-react: 6.200.0
- react: 16.9.0
- react-dom: 16.9.0
- typescript: 3.5.3

Again the same config, but with `office-ui-fabric-react 6.151.0`:
- @angular-react/core: 1.0.1
- @angular-react/fabric: 1.0.2 / 1.0.3
- office-ui-fabric-react: 6.151.0
- react: 16.9.0
- react-dom: 16.9.0
- typescript: 3.5.3

This shows the following errors:
![image](https://user-images.githubusercontent.com/16546287/63345678-90c45a80-c353-11e9-9fe4-217604ffd8a6.png)

It works with `skipLibCheck` though (I assume the other configurations also work with that, but I didn't test it).

I also tried a few combinations of the config which you have in production:
- Angular 8.1.3 / 8.0.2
- @angular-react/core: 1.0.1
- @angular-react/fabric: 1.0.2 / 1.0.3
- office-ui-fabric-react: 6.151.0
- react: 16.8.6
- react-dom: 16.8.6
- typescript: 3.4.5 / 3.5.3

Now it looks like this:
![image](https://user-images.githubusercontent.com/16546287/63345946-32e44280-c354-11e9-9b91-31579050b993.png)
`
An unhandled exception occurred: Object prototype may only be an Object or null: undefined
See "/tmp/ng-BpPmxJ/angular-errors.log" for further details.
`

I'm not sure if this is related to the Angular version or to angular-react.


Summed up, it currently works only with `skipLibCheck`.
Thank you for the help so far, and let me known if you need more information or if I should test another configuration.

**Comment by aarongreenwald** [comment]
Thanks for those tests - I recommend sticking with 6.151.0 for now because we know it's good, and I'm not concerned about those errors. This is apparently a recently-fixed issue in office-ui-fabric-react, see [here](https://github.com/OfficeDev/office-ui-fabric-react/issues/9757). So `skipLibCheck` is an ok workaround for now IMO until we upgrade the dependency in this library. 

I'm going to close for now because I think it shouldn't block anyone's usage, but if I'm wrong please feel free to re-open an issue. 

Sooner or later we're going to have to upgrade to Fabric 7, at which point we'll get the latest updates and fixes from upstream.
