### ISSUE TITLE
Could you add quick start?

### ISSUE THREAD

**Issue by dotandl** [microsoft/angular-react#143]
I found that amazing library and I'd like to use it, but documentation isn't good enough.  
The links in READMEs such as `Documentation, quick start, and guides` go to page that contains some performance tests, components presentations etc., but there is no any documentation, quick start and guides.

And my question is: Could you add these resources?

**Comment by bengry** [comment]
Look in the github wiki. It's very detailed.

**Comment by dotandl** [comment]
Ok, I've read wiki and I know how to use that library. Thanks
