### ISSUE TITLE
how to use fab-grouped-list 

### ISSUE THREAD

**Issue by MarcOne68** [Microsoft/angular-react#71]
Hi, I'm going crazy to understand how to use fab-grouped-list and render a single item.
This is the code:

`<fab-grouped-list [selection]='$Selection' [selectionMode]='$SelectionMode' [groups]='$Groups' [items]='$Items' [renderCell]='myTemplate'></fab-grouped-list>
<ng-template #myTemplate let-######>
    ..........
</ng-template>
`
What should I use instead of ###### to get the item property (index, item, depth) and use them inside the ng-template ?

Thank you

**Comment by bengry** [comment]
@MarcOne68 I take it you figured it out? If there's anything non-trivial we'd appreciate the feedback so we can document it properly.

**Comment by MarcOne68** [comment]
Hi Ben, few minute after I posted the issue I resolved my problem and now it works fine. Thank you
