### ISSUE TITLE
Set selection on fab-details-list

### ISSUE THREAD

**Issue by MarcOne68** [Microsoft/angular-react#78]
Hi,
I'm using a fab-details-list with groups items and I need to select an item programmatically and also to show it (scroll to selected item) and to expand the group that contains the selected item. 
is it possible ? if yes .... how can do it ?
Thanks.

**Comment by bengry** [comment]
@xjerwa can probably assist here.
@MarcOne68. Do you know if that's possible in in the `office-ui-fabric-react` component? The `@angular-react` project is only meant for wrapping existing components and functionality, so  if something not possible in the original component, it won't be in the Angular-wrapped versions either.

**Comment by MarcOne68** [comment]
Thank you @bengry, I'll go to the Office UI fabric react documentation.

**Comment by bengry** [comment]
In closing this for now. If this is possible in the react component and not here, feel free to re-open.
