### ISSUE TITLE
Panel & Dialog both are opened. If you click outside the panel, the panel closes.

### ISSUE THREAD

**Issue by MarcOne68** [Microsoft/angular-react#85]
The issue, for office-ui-fabric-react, is documented here: [https://github.com/OfficeDev/office-ui-fabric-react/issues/7225]. I reproduced the problem with this code:

```
<fab-panel [hasCloseButton]='false' [isBlocking]='true' [isOpen]='true'>
  <fab-default-button text='close' (onClick)='Visible = true'></fab-default-button>
</fab-panel>

<fab-dialog [hidden]='!Visible'>
  <div>Are you sure ?</div>
  <fab-dialog-footer>
    <fab-default-button text='yes'></fab-default-button>
    <fab-primary-button text='no'></fab-primary-button>
  </fab-dialog-footer>
</fab-dialog>
```

although `isBlocking = true` if you click outside the panel, the panel closes.
To resolve the problem, I added this line to the template of `fab-panel`

```
(onOuterClick)='undefined'
```

obviously it's possible to define another event handler:

```
(onOuterClick)='onOuterClick.emit($event)'
```

**Comment by bengry** [comment]
I just took a look at the `FabPanelComponent` and I noticed we aren't handling `onOuterClick` at all (unlike say, `onDismiss` or `onLightDismissClick`). This means that `onOuterClick` should've been passed as `undefined` to begin with, so I'm not sure how your described fix solves it. I'll need to take a deeper look.

If you have the time - feel free to try that, and if it works - submit a PR, I'll be happy to review it. If not, I'll try to get to looking at this soon.
