### ISSUE TITLE
Support for ngModel and two way data binding

### ISSUE THREAD

**Issue by eswarpr** [Microsoft/angular-react#90]
At present none of the input components support using ngModel to allow support for two way data binding and usage in forms within Angular applications. The proposal below attempts to address that:

### New abstract base class for input components
I propose a simple abstract base class that all input components can derive from. It should provide the necessary plumbing to support `NG_VALUE_ACCESSOR` for individual input components, but should also allow sufficient amount of flexibility for individual input components to implement support for it. The proposed base class should be named `FabInputComponent` which inherits from `ReactWrapperComponent`

### ngModel specific methods
The abstract base class will define 2 abstract methods: `onModelValueChanged` and `onViewValueChanged` which will allow inherited input component to react and respond to framework events pertaining to ngModel bindings. The input components will then implement their own logic to handle those events. For e.g. `FabDropdownComponent` will use these events to set it's internal `selectedKey` property as well as use the `onViewValueChanged` to provide feedback to the framework when a drop down option is selected by the user.

### Current status
I have a blueprint of this implementation working in one of my fork branches. There is a case for this to be reviewed by the community since these are fundamental changes to some of the widely used components in the library.

**Comment by bengry** [comment]
@eswarpr I'm not sure - on the one hand, from the viewpoint of applications, this is great - it's the syntax they already know, for more components. On the other, it means more maintenance in the `@angular-react` side of things, which is something we'd like to avoid, at least while we don't have an automated/semi-automated way of generating components.

Another concern is that once something like `fab-text-field` uses this, it means that you must also use `FormsModule`, which in theory at least, means a bigger bundle size for your app (i.e. apps can use `@angular-react` without `@angular/forms` so far). This is probably a non-issue for the most part though in real apps.

I'd appreciate it if you could add a link to a repo with the changes needed and I'll take a look.

**Comment by eswarpr** [comment]
@bengry agree on the dependency side and maintainance side of things. On the flip side, developers will find it easy to use these components in forms. Important thing for me was to keep the prop mappings as they are but adding support for value accessor. There maybe a better way to do it - such as the way Material components work by wrapping them in a sort of `fab-form-field` directive, but haven't thought deeply about it yet. 

I will post a link to my code ASAP

**Comment by bengry** [comment]
I haven't checked out how Material does this. But a directive sounds like a good approach. It can be added as part of a sibling module to each component module, or as another package even. Then `@angular/forms` becomes an optional dependency.

Additionally, since the form bindings are just syntax sugar over the already-exposed public APIs, this makes lots of sense as a directive.

If you're willing to give implementing this a try I'd be happy to help and interested in in getting this into the library.
